# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutustxt', models.TextField()),
                ('aboutustitle', models.CharField(max_length=100)),
                ('aboutusimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
            ],
        ),
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumname', models.CharField(blank=True, max_length=100, null=True)),
                ('albumimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('albumcontent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companylogo', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('companyname', models.CharField(blank=True, max_length=200, null=True)),
                ('companymessage', models.CharField(blank=True, max_length=300, null=True)),
                ('companytext', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryname', models.CharField(blank=True, max_length=100, null=True)),
                ('galleryimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('homecontent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('logourl', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsnme', models.CharField(blank=True, max_length=100, null=True)),
                ('newsimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('newscontent', models.TextField(blank=True, null=True)),
                ('newsdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotionname', models.CharField(blank=True, max_length=100, null=True)),
                ('promotionimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(blank=True, max_length=100, null=True)),
                ('serviceimgae', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('servicecontent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderimage', models.FileField(upload_to='documents/media')),
                ('slidername', models.CharField(blank=True, max_length=100, null=True)),
                ('slidermessage', models.CharField(blank=True, max_length=100, null=True)),
                ('slidercontent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourname', models.CharField(blank=True, max_length=100, null=True)),
                ('tourimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
                ('tourcontent', models.TextField(blank=True, null=True)),
                ('tourdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitimage', models.FileField(blank=True, null=True, upload_to='documents/media')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(blank=True, max_length=200, null=True)),
                ('videourl', models.CharField(max_length=500)),
            ],
        ),
    ]
